@echo off
chcp 65001 >nul
echo ===================================================================
echo   Linux WeChat Pay Callback Service - Configuration Wizard
echo ===================================================================
echo.

if exist config.env (
    echo Found existing config.env
    set /p reconfig="Reconfigure? (y/N): "
    if /i not "%reconfig%"=="y" (
        echo Using existing config.
        exit /b 0
    )
    del config.env
)

echo Please enter callback configuration:
echo Callback URL is used to receive WeChat payment notifications
set /p callbackIP="Callback IP (default: host.docker.internal): "
if "%callbackIP%"=="" set callbackIP=host.docker.internal

set /p callbackPort="Callback port (default: 5000): "
if "%callbackPort%"=="" set callbackPort=5000

set /p callbackSecret="Callback secret (default: test_secret): "
if "%callbackSecret%"=="" set callbackSecret=test_secret

echo.
echo Please enter VNC configuration:
set /p vncPassword="VNC password (default: wechat123): "
if "%vncPassword%"=="" set vncPassword=wechat123

set /p vncResolution="VNC resolution (default: 1280x800): "
if "%vncResolution%"=="" set vncResolution=1280x800

echo.
set /p timezone="Timezone (default: Asia/Shanghai): "
if "%timezone%"=="" set timezone=Asia/Shanghai

(echo # Linux WeChat Pay Callback Service - Config File
echo # Generated by setup.bat
echo.
echo # Callback Config
echo CALLBACK_URL=http://%callbackIP%:%callbackPort%/api/payment/notify/linux_wechat
echo CALLBACK_SECRET_KEY=%callbackSecret%
echo.
echo # VNC Config
echo VNC_PW=%vncPassword%
echo VNC_RESOLUTION=%vncResolution%
echo.
echo # Timezone
echo TZ=%timezone%) > config.env

echo.
echo ===================================================================
echo Config file generated: config.env
echo ===================================================================
echo.
echo Config content:
type config.env
echo.
echo ===================================================================
echo Next steps:
echo 1. Check config.env
echo 2. Run: docker-compose -f docker-compose.vnc.yml up -d
echo 3. Visit: http://localhost:6080/vnc.html
echo ===================================================================
